# -*- coding: utf-8 -*-
"""Broadcasting in Python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4fKshTuwW9pSfR-vVBwibnkqei79Fep
"""

import numpy as np
A= np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

cal = A. sum(axis=0)
print(cal)

percentage = 100*A/cal.reshape(1,4)
print(percentage)