# -*- coding: utf-8 -*-
"""Numpy Vectors.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4fKshTuwW9pSfR-vVBwibnkqei79Fep
"""

import numpy as np
a= np.random.randn(5)
print (a)

print(a.shape)

print(a.T)

print(np.dot(a,a.T))

a=np.random.randn(5,1)
print(a)



print(a.T)

print(np.dot(a,a.T))