# -*- coding: utf-8 -*-
"""Vectorized  Example.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1W4fKshTuwW9pSfR-vVBwibnkqei79Fep
"""

import numpy as np
a= np.array([1,2,3,4])
print(a)

import time
a= np.random.rand(1000000)
b= np.random.rand(1000000)
tic= time.time()
c= np.dot(a,b)
tac= time.time()
print(c)
print("Vectorized version : "+ str(1000*(tac-tic))+ "ms")
c=0;
tic = time.time()
for i in range(1000000):
  c+=a[i]*b[i]
tac= time.time()
print(c)
print("For Loop : "+ str(1000*(tac-tic))+ "ms")